<?php

return [

    "city_vn" => [
        1 => "Hồ Chí Minh",
        2 => "Hà Nội",
        3 => "Đà Nẵng",
        4 => "Bình Dương",
        5 => "Đồng Nai",
        6 => "Khánh Hòa",
        7 => "Hải Phòng",
        8 => "Long An",
        9 => "Quảng Nam",
        10 => "Bà Rịa Vũng Tàu",
        11 => "Đắk Lắk",
        12 => "Cần Thơ",
        13 => "Bình Thuận",
        14 => "Lâm Đồng",
        15 => "Thừa Thiên Huế",
        16 => "Kiên Giang",
        17 => "Bắc Ninh",
        18 => "Quảng Ninh",
        19 => "Thanh Hóa",
        20 => "Nghệ An",
        21 => "Hải Dương",
        22 => "Gia Lai",
        23 => "Bình Phước",
        24 => "Hưng Yên",
        25 => "Bình Định",
        26 => "Tiền Giang",
        27 => "Thái Bình",
        28 => "Bắc Giang",
        29 => "Hòa Bình",
        30 => "An Giang",
        31 => "Vĩnh Phúc",
        32 => "Tây Ninh",
        33 => "Thái Nguyên",
        34 => "Lào Cai",
        35 => "Nam Định",
        36 => "Quảng Ngãi",
        37 => "Bến Tre",
        38 => "Đắk Nông",
        39 => "Cà Mau",
        40 => "Vĩnh Long",
        41 => "Ninh Bình",
        42 => "Phú Thọ",
        43 => "Ninh Thuận",
        44 => "Phú Yên",
        45 => "Hà Nam",
        46 => "Hà Tĩnh",
        47 => "Đồng Tháp",
        48 => "Sóc Trăng",
        49 => "Kon Tum",
        50 => "Quảng Bình",
        51 => "Quảng Trị",
        52 => "Trà Vinh",
        53 => "Hậu Giang",
        54 => "Sơn La",
        55 => "Bạc Liêu",
        56 => "Yên Bái",
        57 => "Tuyên Quang",
        58 => "Điện Biên",
        59 => "Lai Châu",
        60 => "Lạng Sơn",
        61 => "Hà Giang",
        62 => "Bắc Kạn",
        63 => "Cao Bằng"
    ]

];
